### ISSUE TITLE
Need to clarify certain items of the expanded schema

### ISSUE THREAD

**Issue by HelenaSabel** [BetaMasaheft/Schema#15]
I am comparing the ODDs `tei-betamesaheft.xml` and `tei-betamesaheft-expanded.xml` to evaluate the elements that both schemas have in common. The objective is to redesign `tei-betamesaheft-expanded.xml` so that it uses `tei-betamesaheft.xml` as its source ODD, thus facilitating the automatic update of the expanded version.

I have a few questions concerning the relation between  `tei-betamesaheft.xml` (from now on, _source_ schema) and `tei-betamesaheft-expanded.xml` (from now on, _expanded_ schema). In most cases, it’s just a matter of confirming “yes, this is what we want”.

1. Concerning attribute definitions, in most cases the main difference is that the list of values in the source schema is defined as closed, and in the expanded version as semi-open (which makes perfect sense from a conceptual point of view). I would like to confirm nevertheless that this is indeed the expected behaviour and that the expanded version should not have a closed list as in the source. I provide a few examples of this case:
     - `del/@rend`
     - `binding/@contemporary`
     - `add/@place`
     - `erm/@key`
     - `language/@ident`
     - `ref/@type`
3. The second most frequent difference is that an attribute is defined in the source as required, but as optional in the expanded version. Is this the wanted behaviour? I wonder if the usage of these attributes shouldn’t at least be recommended in the expanded version (if indeed they shouldn’t be required).
4. This is less frequent, but there are also some attributes that go from a recommended use to an optional one. Shouldn’t they also be recommended in the expanded version (e.g. `seg/@type`)
5. Concerning the lists of attribute values, I found a few cases in which the source schema had more values than the expanded schema. I considered that these were precisely the cases in which the expanded schema could be “out of sync” in relation to its source (since to my understanding, the expanded schema should contain at least all the values available in the source): is this assumption correct.
6. I also found attribute values in the expanded version not available in the source. While it makes sense conceptually, I would like to confirm that this is indeed correct in the following cases:
     1. `desc/@type`
     2. `persName/@role`: the expanded schema contains the value “tabot” (this value is also available in `persName/@type` in both schemas).
     3. `listBibl/@type`: the value “mss” is provided in the expanded schema but not in the source one.
7. For some elements, the expanded schema has exactly the same schematron rules than the source schema. In some cases, however, we only find constraints in the source. I would like to confirm that the constraints of the following elements in the source should be overwritten in the expanded version (or if, on the other hand, they should be present in the expanded schema as well):
     - `date`
     - `ref`
     - `listBibl`
     - `roleName`
     - `witness`
     - `dimensions`
     - `seg`
     - `msPart`
     - `change`
     - `persName`
     - `div`
     - `item`
     - `damage`
 
8. For the element `geo`, the source schema contains different constraints depending on the presence of the attribute `@rend`. In the expanded schema, we find just one constraint for the element `geo` (that matches the rule of the source for `geo[not(@rend)]`. I would like to confirm that the expanded schema is correct and this is indeed the wanted behaviour.
 9. The number of constraints for the element `locus` is also bigger in the source than in the expanded schema. Should all the constraints for the source be imported in the expanded version or should they be replaced?
 10.  The element `creation` contains the definition of an attribute `@evidence` which is not available in the expanded version: is this correct?

**Comment by eu-genia** [comment]
Yes, the expanded schema must be more relaxed.

The reason for this is that expanded schema should 

- (1) validate the expanded files produced on the app, which are different from the TEI files we work with
- (2) validate the files produced by other projects (e.g. IslHornAfr) which do not follow the Bm schema and use different values (therefore the lists are open)

We for Bm produce files of the type stored in BetMasData repository on the app (same as here on GitHub) which use the tei-betamesaheft.xml schema.

The files which are used by the app for visualization are stored in "expanded" repository only available online and produced by expand.xqm script triggered by the gitsync; we do not locally validate them and we do not actively use the expanded schema. 

The missing elements however should surely be added, it must be because I have not updated the expanded schema for a while and so it is out of sync.

**Comment by HelenaSabel** [comment]
Thank you for the prompt answer, @eu-genia.

I have another question, if I may. In the definition of `origDate` in the source ODD (see https://github.com/BetaMasaheft/Schema/blob/cf152cf5f8b77749734c076e8aed411400dd2c63/tei-betamesaheft.xml#L590) we don’t have a specific definition for the attribute `@type` (although there was one likely at some point, seeing the comment). In the expanded version we do have this definition of values for  `@type`.  Should this definition also disappear from the expanded version?

**Comment by eu-genia** [comment]
i guess the error is in the comment, the values suggested are for ` @evidence` (so here `type `stands for `evidence`, this is the attribute we use), for me expanded looks the same here

**Comment by HelenaSabel** [comment]
Hi @eu-genia! In the expanded version, if you look at lines 118-129 you see the attribute values for an attribute `@type` in `<origDate>`

**Comment by eu-genia** [comment]
Sorry I must be confused. Am I looking in a wrong place? https://github.com/BetaMasaheft/Schema/blob/master/tei-betamesaheft-expanded.xml

**Comment by HelenaSabel** [comment]
Yes, that’s the file (apologies, the line numbers in the previous message were not the correct ones). In that file, in lines 307-317 you can see the attribute values for an attribute `@type` in `<origDate>`. But this `@type` for that element attribute is not defined in `tei-betamesaheft.xml`

**Comment by eu-genia** [comment]
i see, you are right. i think they can be removed

**Comment by HelenaSabel** [comment]
Perfect! Thank you for your answers @eu-genia. I don’t have any other doubts, so I will close the ticket.
